import React, { useRef } from 'react';
import { AccumulativeShadows, RandomizedLight } from '@react-three/drei';

const Backdrop = () => {
  const shadows = useRef();

  return (
    <AccumulativeShadows
      ref={shadows}
      temporal // shadows appear over time instead of instantaneously for more smoothness
      frames={60} //# of frames over which the shadows appear
      alphaTest={0.85} // higher alpha = less transparent shadows
      scale={10} // higher scale = more sharp shadows but more mem & processing power
      rotation={[Math.PI / 2 , 0, 0]} // rotation of shadow map texture
      position={[0,0,-0.14]} // position of shadow relative to 3D scene
    >
      <RandomizedLight 
        amount={4} // # of lights generated by component
        radius={9} // radius of area from which random lights will be generated
        intensity={0.55} // brightness
        ambient={0.25} // brightness of ambient light in the scene
        position={[5,5,-10]} // position of center of area from which lights will be generated
      />
      <RandomizedLight 
        amount={4}
        radius={5}
        intensity={0.25}
        ambient={0.55}
        position={[-5,5,-9]}
      />
    </AccumulativeShadows>
  )
}

export default Backdrop